# Generated by Django 3.2 on 2023-07-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0004_contact_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
    ]
