# Generated by Django 3.2 on 2023-07-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0006_auto_20230729_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
