# Generated by Django 3.2 on 2023-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0011_alter_blog_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
