# Generated by Django 3.2 on 2023-07-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0013_remove_blog_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_date']},
        ),
    ]
