# Generated by Django 3.2 on 2023-07-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0014_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
